from DBHelper.tables.achievement import Achievement
from DBHelper.tables.achievement_title_book import AchievementTitleBook
from DBHelper.tables.battle_status import BattleStatus
from DBHelper.tables.box import Box
from DBHelper.tables.dust import Dust
from DBHelper.tables.equipment import Equipment
from DBHelper.tables.equipment_gem_record import EquipmentGemRecord
from DBHelper.tables.equipment_quality_dust_num import EquipmentQualityDustNum
from DBHelper.tables.equipment_star_record import EquipmentStarRecord
from DBHelper.tables.exp_book import ExpBook
from DBHelper.tables.gem import Gem
from DBHelper.tables.holiday import Holiday
from DBHelper.tables.identify_book import IdentifyBook
from DBHelper.tables.initial_skill_achievement_equipment_potion_etc_properties import \
    InitialSkillAchievementEquipmentPotionEtcPropertiesRecord as MiscProperties  # 目前唯一简写
from DBHelper.tables.monster import Monster
from DBHelper.tables.monster_show_up_record import MonsterShowUpRecord
from DBHelper.tables.open_decompose_or_drop_stuffs import OpenDecomposeOrDropStuffsRecord
from DBHelper.tables.pk_rank import PK_Rank
from DBHelper.tables.player import Player
from DBHelper.tables.player_achievement_record import PlayerAchievementRecord
from DBHelper.tables.player_battle_record import PlayerBattleRecord
from DBHelper.tables.player_level_exp_skill_point import PlayerLevelExpSkillPoint
from DBHelper.tables.player_lottery_record import PlayerLotteryRecord
from DBHelper.tables.player_mail_record import PlayerMailRecord
from DBHelper.tables.player_or_monster_skill_setting import PlayerOrMonsterSkillSetting
from DBHelper.tables.player_potion_record import PlayerPotionRecord
from DBHelper.tables.player_sell_store_record import PlayerSellStoreRecord
from DBHelper.tables.player_skill_record import PlayerSkillRecord
from DBHelper.tables.player_stuff_record import PlayerStuffRecord
from DBHelper.tables.player_use_book_record import PlayerUseStuffRecord
from DBHelper.tables.potion import Potion
from DBHelper.tables.raise_star_book import RaiseStarBook
from DBHelper.tables.raise_star_prob import RaiseStarProb
from DBHelper.tables.setting import Setting
from DBHelper.tables.skill import Skill
from DBHelper.tables.skill_book import SkillBook
from DBHelper.tables.skill_cost_point import SkillCostPoint
from DBHelper.tables.skill_slot import SkillSlot
from DBHelper.tables.tips import Tips
from DBHelper.tables.world_hero_medal import WorldHeroMedal
