import DBHelper.tables.achievement as achievement
import DBHelper.tables.base_property_additional_property as base_property_additional_property
import DBHelper.tables.battle_status as battle_status
import DBHelper.tables.box as box
import DBHelper.tables.equipment as equipment
import DBHelper.tables.equipment_gem_record as equipment_gem_record
import DBHelper.tables.exp_book as exp_book
import DBHelper.tables.gem as gem
import DBHelper.tables.holiday as holiday
import DBHelper.tables.identify_book as identify_book
import DBHelper.tables.initial_skill_achievement_equipment_potion_etc_properties as misc_properties    # 目前唯一简写
import DBHelper.tables.monster as monster
import DBHelper.tables.monster_show_up_record as monster_show_up_record
import DBHelper.tables.monster_skill_record as monster_skill_record
import DBHelper.tables.open_decompose_or_drop_stuffs as open_decompose_or_drop_stuffs
import DBHelper.tables.player as player
import DBHelper.tables.player_achievement_record as player_achievement_record
import DBHelper.tables.player_battle_record as player_battle_record
import DBHelper.tables.player_level_exp_skill_point as player_level_exp_skill_point
import DBHelper.tables.player_lottery_record as player_lottery_record
import DBHelper.tables.player_mail_record as player_mail_record
import DBHelper.tables.player_or_monster_skill_setting as player_or_monster_skill_setting
import DBHelper.tables.player_potion_record as player_potion_record
import DBHelper.tables.player_sell_store_record as player_sell_store_record
import DBHelper.tables.player_skill_record as player_skill_record
import DBHelper.tables.player_stuff_record as player_stuff_record
import DBHelper.tables.potion as potion
import DBHelper.tables.raise_star_book as raise_star_book
import DBHelper.tables.raise_star_prob as raise_star_prob
import DBHelper.tables.setting as setting
import DBHelper.tables.skill as skill
import DBHelper.tables.skill_book as skill_book
import DBHelper.tables.skill_cost_mana as skill_cost_mana
import DBHelper.tables.skill_cost_point as skill_cost_point
